#!/usr/bin/env bash
# Check if running as root user
if [[ $EUID -ne 0 ]]; then
	echo 'Please run this script as root or sudo'
	exit 1
fi

if [ $# -eq 1 ]; then
	sudo apt update -y
	sudo apt install snapd -y
	sudo apt-get remove certbot -y
	sudo apt-get install certbot -y
	sudo service haproxy stop -y

	MY_DOMAIN="$1"
	sudo certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d "$MY_DOMAIN" -d  "$MY_DOMAIN"
	sudo ls /etc/letsencrypt/live/"$MY_DOMAIN"
	sudo mkdir -p /etc/haproxy/certs

	sudo -E bash -c 'cat /etc/letsencrypt/live/$MY_DOMAIN/fullchain.pem /etc/letsencrypt/live/$MY_DOMAIN/privkey.pem > /etc/haproxy/certs/$MY_DOMAIN.pem'
	sudo chmod -R go-rwx /etc/haproxy/certs
	sudo vi /etc/haproxy/haproxy.cfg
	sudo service haproxy start	
else
	SCRIPT_NAME=$(basename "$0")
	echo  "Usage: sudo ./certbot <malloshub.tech>"
fi
