#!/usr/bin/env bash
# script to install nginx

apt-get update
apt install nginx -y
ufw enable -y
sed -i 's/.*listen\s*80.*/        listen 80;/g' /etc/nginx/nginx.conf
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
