#!/usr/bin/env bash
# A script to install nginx web server and configure it to redirect_me
# to another page.

sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello world!" | sudo tee /etc/nginx/html/index.html

sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
       return 301 https://www.youtube.com/watch?v=RgtNZGA6NYQ;
   }
}" | sudo tee  /etc/nginx/sites-available/default
sudo service nginx restart

