#!/usr/bin/env bash
# Script to install nginx web server

sudo apt-get update
sudo apt-get install nginx -y

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello world!" > /etc/nginx/html/index.html
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

 #    location /redirect_me {
 #       return 301 http://cuberule.com/;
 #   }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
