#!/usr/bin/env bash
# A script to install nginx web server and configure it to redirect_me
# to another page.

sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir -p /var/www/nginx/html
sudo touch /var/www/nginx/html/index.html
echo "Hello world!" | sudo tee /var/www/nginx/html/index.html

# This is Nginx default page (/etc/nginx/sites-availalbe/default) Server block
# setting. It accepts the following codes:
# (1) Port the server should listen to, (2) Root directory of the default page
# (3) Format to accept for index page   (4) Action and location for redirect_me
# (5) Action and location for error Page
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
       return 301 https://www.youtube.com/watch?v=RgtNZGA6NYQ/;
   }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
      add_before_body /404.html;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Creating the custom 404 error page with the added text
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

sudo service nginx restart
