#!/usr/bin/env bash
# A script to install nginx web server and configure it to redirect_me
# to another page

sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir -p /var/www/nginx/html
sudo touch /var/www/nginx/html/index.html
# replacing > with "| sudo tee" because of the sudo command
echo "Hello World!" | sudo tee /var/www/nginx/html/index.html
# Creating the custom 404 error page with the added text
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# This is Nginx default page (/etc/nginx/sites-availalbe/default) Server block
# setting. It accepts the following codes:
# (1) Port the server should listen to, (2) Root directory of the default page
# (3) Format to accept for index page   (4) Action and location for redirect_me
# (5) Action and location for error Page
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/nginx/html;
    # Add all the prefixes .php, . com .tech
    index index.html index.htm index.nginx-debian.html index.php;

    server_name _;
    # What to display when you type url/redirect_me
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=RgtNZGA6NYQ/;

    # When user tries url/404 or url/unexisitng page, it displays 404.html page
    error_page 404 /404.html;
    location /404.html {
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
