#!/usr/bin/env bash
# iInstall and configure HAproxy on your lb-01 server.

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

# edit config file
HAproxy_config="frontend  malloshub-frontend
        bind *:80
        mode http
        default_backend malloshub-backend
backend malloshub-backend
        balance roundrobin
        server 179905-web-01 18.210.17.153:80 check
        server 179905-web-02 100.25.183.151:80 check
"
echo "$HAproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg
