#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy -y
sudo apt-get install haproxy -y
sudo apt-get -y update

# edit config file
HAproxy_config=\
"frontend malloshub-frontend
        bind *:80
        mode http
        default_backend malloshub-backend

backend malloshub-backend
        balance roundrobin
        server 179905-web-01 54.226.23.250:80 check
        server 179905-web-02 100.25.183.151:80 check

listen http-in
        bind *:80
        balance roundrobin
        server 179905-web-01 54.226.23.250:80 check
        server 179905-web-02 100.25.183.151:80 check
"

echo "$HAproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
