#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.

touch "/var/run/myscript.pid"
while true
do
  echo "To infinity and beyond"
  sleep 2
   trap "echo I hate the kill command" SIGTERM
  trap "echo Y U no love me?!" SIGINT
  pkill -f -3 "rm /var/run/myscript.pid"
done
