#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#    display hours from 0 to 12
#    display minutes from 1 to 59
#    Requirements:
#        You must use the while loop (for and until are forbidden)

hr=0

while (( hr <= 12 ))
do
  min=1
  echo "Hour: $hr"

  while (( min <= 59 ))
  do
    echo "$min"
    (( min++ ))
  done
  (( hr++ ))
done
