#!/usr/bin/env bash
## To install ufw
sudo apt update -y
sudo apt install ufw -y

# To deny all incoming and allow outgoing connections respectively
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y

# To allow ssh, http and https connections respectively
sudo ufw allow 22/ssh
sudo ufw allow 80/http
sudo ufw allow 443/https

# To enable and view status respectively
sudo ufw enable
sudo ufw status numbered
