#!/usr/bin/env bash
# script to install nginx
sudo apt-get update
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www/html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
